version: '3'

services:
  sr_postgres:
    image: postgres:latest
    container_name: sr_postgres
    ports:
       - "5432:5432"
    volumes:
      - sr_postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: sr_admin
      POSTGRES_PASSWORD: dev2original
      POSTGRES_DB: space_repetition

  pgadmin:
      container_name: pgadmin
      image: dpage/pgadmin4
      environment:
        PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
        PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      volumes:
        - pgadmin:/root/.pgadmin
      ports:
        - "${PGADMIN_PORT:-5050}:80"

volumes:
  sr_postgres:
  pgadmin:
